# Generated by Django 3.2.13 on 2022-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_status',
            field=models.CharField(default='online', max_length=8),
        ),
    ]
