# Generated by Django 3.2.13 on 2022-04-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_status_count',
            field=models.IntegerField(default=0),
        ),
    ]
