# Generated by Django 3.2.13 on 2022-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profile_online_status_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='online_status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatar/'),
        ),
    ]
