# Generated by Django 3.2.13 on 2022-04-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20220429_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/'),
        ),
    ]
