# Generated by Django 3.2.13 on 2022-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20220430_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='read_status',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
