# Generated by Django 3.2.13 on 2022-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_url_display',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
