# Generated by Django 3.2.13 on 2022-05-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_url_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_url_display',
        ),
    ]
